# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04a75492cfbb8a89bedb316fee5d5df94e6ad383b46ba5044beb174d9d5dd80033d4f36e09bce3321efbea9b971429b6f89c824947c821d47f3d83a5cd56afab

test:
  secret_key_base: cd0b2593bca223021a75ddd0f21870f696cf12b6c774d7cb57683b4529f68706f0a1ec4e69a4fc49483d47d00f71499ea59df8cb093dbc1297b8c27128bee29d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
